### PR TITLE
Now implementing 'ActionBarDrawerToggle'

### PR DESCRIPTION
**Pull request by LukeStonehm**
UPDATED:    

• Now implementing 'ActionBarDrawerToggle' 
                          -> uses built in drawer icon (with nice built in animation) OCD fix.
                          -> Is the correct way to implement NavDrawer with latest support libs.
• added "open"& "close" string -> inconsequential strings, user will never see these strings, but function requires them. Translate strings when you can :)

### CODE REVIEW

**Comment by albertvaka** [comment]
Why is this approach better than using the default button and not creating an ActionBarDrawerToggle? I saw both ways to do it initially, and I went for the current one as it has less moving pieces. Do you know the pros and cons?

**Comment by LukeStonehm** [comment]
Just to clarify, your approach is fine (I think, I read somewhere that the "setDrawerIcon" function will soon be depreciated in the newer support libs).

My approach conforms to Google's guideline for implementing a NavDrawer. It is future proof, as should you ever want to listen for open / close events, the framework is there. It now uses the built in icon (which differs per API, and so now it will render correctly regardless of API). It also now has the nice icon animation, which is pointless since the navDrawer covers it, but it's there so my OCD is appeased :smile:  

I referenced the following: https://developer.android.com/training/implementing-navigation/nav-drawer.html

This is more an issue of "semantics" I think. It's a non-issue, but I tend to like things to be perfect. I intend to submit more changes, when I have time and find issues I think I can fix :smile:

**Comment by albertvaka** [comment]
Keep the patches comming then :D

**Comment by LukeStonehm** [comment]
Thank you for the merge good sir! Have a good week further :smile:

**Pull request merged**
